apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    prometheus: cluster_scanning_rule
    role: alert-rules
  name: prom-trivy-scanner-rules
  namespace: monitoring
spec:
  groups:
  - name: VulnerabilityAlerts
    rules:
    - alert: TrivyCriticalVulnerabilitiesDetected
      expr: sum(trivy_image_vulnerabilities{severity="Critical"}) > 0
      for: 30s
      labels:
        severity: critical
      annotations:
        summary: "Critical Vulnerabilities Detected by Trivy"
        description: |
          Trivy has detected critical vulnerabilities in the cluster. Severity is critical,
          requiring immediate attention.
        details: |
          Vulnerabilities of critical severity have been reported by Trivy for workloads in the cluster.
          Review and mitigate these issues immediately to secure the environment.
